
CMDRAW_SAVE_ADDRESS_LONG:
	JSR .continue

	LDA.b [SA1IRAM.cm_current_draw], Y
	STA.b SA1IRAM.cm_writer+2
	INY
	RTS

#CMDRAW_SAVE_ADDRESS_00:
	SEP #$20
	STZ.b SA1IRAM.cm_writer+2

.continue
	REP #$20
	LDA.b [SA1IRAM.cm_current_draw], Y
	INY
	INY

	STA.b SA1IRAM.cm_writer+0

	SEP #$20
	RTS

;===============================================================================
CMDRAW_WORD_LONG:
	PHP
	REP #$30
	PHY
	PHB
	PHA

	SEP #$20
	LDA.b SA1IRAM.cm_writer+2
	PHA
	PLB

	REP #$20
	BRA .continue

#CMDRAW_WORD:
	PHP
	REP #$30
	PHY

	PHB
	PHK
	PLB

	PHA

.continue
	LDY.w #0

.next
	LDA (1,S),Y
	AND.w #$00FF
	CMP.w #$00FF
	BEQ .done

	ORA.b SA1IRAM.cm_draw_color
	STA.w SA1RAM.MENU, X
	INX
	INX
	INY
	BRA .next


.done
	PLA
	PLB

	REP #$30
	PLY
	PLP
	JMP EmptyCurrentRow_from_here_to_end

CMDRAW_RANDOM:
	REP #$20
	PLA
	PHK
	PHA
.long
	REP #$20
	LDA.w #.text
	JSR CMDRAW_WORD
	RTL

.text
	db "RANDOM", $FF

CMDRAW_ON:
	REP #$20
	PLA
	PHK
	PHA
.long
	REP #$20
	LDA.w #.text
	JSR CMDRAW_WORD
	RTL

.text
	db "ON", $FF

CMDRAW_YES:
	REP #$20
	PLA
	PHK
	PHA
.long
	REP #$20
	LDA.w #.text
	JSR CMDRAW_WORD
	RTL

.text
	db "YES", $FF

CMDRAW_OFF:
	REP #$20
	PLA
	PHK
	PHA
.long
	REP #$20
	LDA.w #.text
	JSR CMDRAW_WORD
	RTL

.text
	db "OFF", $FF

CMDRAW_NO:
	REP #$20
	PLA
	PHK
	PHA
.long
	REP #$20
	LDA.w #.text
	JSR CMDRAW_WORD
	RTL

.text
	db "NO", $FF

CMDRAW_HEX:
	SEP #$20
	PHA

	JSR .tohex
	STA.w $0001

	PLA
	LSR
	LSR
	LSR
	LSR
	JSR .tohex
	STA.w $0000

	LDA.b #$FF
	STA.w $0002

	REP #$20
	LDA.w #$0000
	JSR CMDRAW_WORD

	RTL

.tohex
	AND.b #$0F
	CMP.b #$0A
	BCC .numeral

	SBC.b #$0A
	RTS

.numeral
	ORA.b #$20
	RTS

.long
	PHB
	PHK
	PLB
	JSR CMDRAW_HEX
	PLB
	RTL


;===============================================================================
CMDRAW_TOGGLE_BIT0:
	LDA.b #$1<<0 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT1:
	LDA.b #$1<<1 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT2:
	LDA.b #$1<<2 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT3:
	LDA.b #$1<<3 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT4:
	LDA.b #$1<<4 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT5:
	LDA.b #$1<<5 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT6:
	LDA.b #$1<<6 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE_BIT7:
	LDA.b #$1<<7 : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_TOGGLE:
CMDRAW_TOGGLE_FUNC:
	LDA.b #$FF : BRA CMDRAW_CHECK_BIT_LOCAL

CMDRAW_CHECK_BIT_LONG:
	PHA
	JSR CMDRAW_SAVE_ADDRESS_LONG
	BRA .continue

#CMDRAW_CHECK_BIT_LOCAL:
	PHA
	JSR CMDRAW_SAVE_ADDRESS_00

.continue
	PLA
	AND.b [SA1IRAM.cm_writer]
	BNE ++

	JMP CMDRAW_NO
++	JMP CMDRAW_YES

CMDRAW_TOGGLE_LONG:
CMDRAW_TOGGLE_LONG_FUNC:
	LDA.b #$FF : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT7_LONG:
	LDA.b #$1<<7 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT6_LONG:
	LDA.b #$1<<6 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT5_LONG:
	LDA.b #$1<<5 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT4_LONG:
	LDA.b #$1<<4 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT3_LONG:
	LDA.b #$1<<3 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT2_LONG:
	LDA.b #$1<<2 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT1_LONG:
	LDA.b #$1<<1 : BRA CMDRAW_CHECK_BIT_LONG

CMDRAW_TOGGLE_BIT0_LONG:
	LDA.b #$1<<0 : BRA CMDRAW_CHECK_BIT_LONG

;-------------------------------------------------------------------------------

CMDRAW_TOGGLE_BIT0_CUSTOMTEXT:
	LDA.b #$1<<0 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT1_CUSTOMTEXT:
	LDA.b #$1<<1 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT2_CUSTOMTEXT:
	LDA.b #$1<<2 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT3_CUSTOMTEXT:
	LDA.b #$1<<3 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT4_CUSTOMTEXT:
	LDA.b #$1<<4 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT5_CUSTOMTEXT:
	LDA.b #$1<<5 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT6_CUSTOMTEXT:
	LDA.b #$1<<6 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_BIT7_CUSTOMTEXT:
	LDA.b #$1<<7 : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_TOGGLE_CUSTOMTEXT:
CMDRAW_TOGGLE_FUNC_CUSTOMTEXT:
	LDA.b #$FF : BRA CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT

CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT:
	PHA
	JSR CMDRAW_SAVE_ADDRESS_LONG
	BRA .continue

#CMDRAW_CHECK_BIT_LOCAL_CUSTOMTEXT:
	PHA
	JSR CMDRAW_SAVE_ADDRESS_00

.continue
	PLA
	AND.b [SA1IRAM.cm_writer]
	PHP

	JSR CMDRAW_SAVE_ADDRESS_LONG
	LDY.b #0

	PLP
	BNE .on

	LDY.b #2

.on
	REP #$20
	LDA.b [SA1IRAM.cm_writer], Y
	JMP CMDRAW_WORD_LONG

CMDRAW_TOGGLE_LONG_CUSTOMTEXT:
CMDRAW_TOGGLE_LONG_FUNC_CUSTOMTEXT:
	LDA.b #$FF : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT7_LONG_CUSTOMTEXT:
	LDA.b #$1<<7 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT6_LONG_CUSTOMTEXT:
	LDA.b #$1<<6 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT5_LONG_CUSTOMTEXT:
	LDA.b #$1<<5 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT4_LONG_CUSTOMTEXT:
	LDA.b #$1<<4 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT3_LONG_CUSTOMTEXT:
	LDA.b #$1<<3 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT2_LONG_CUSTOMTEXT:
	LDA.b #$1<<2 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT1_LONG_CUSTOMTEXT:
	LDA.b #$1<<1 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

CMDRAW_TOGGLE_BIT0_LONG_CUSTOMTEXT:
	LDA.b #$1<<0 : BRA CMDRAW_CHECK_BIT_LONG_CUSTOMTEXT

;===============================================================================
CMDRAW_NUMFIELD:
CMDRAW_NUMFIELD_LONG:
CMDRAW_NUMFIELD_FUNC:
CMDRAW_NUMFIELD_LONG_FUNC:
CMDRAW_CTRL_SHORTCUT:
CMDRAW_CTRL_SHORTCUT_FINAL:
CMDRAW_CHOICE:
CMDRAW_CHOICE_LONG:
CMDRAW_CHOICE_PRGTEXT:
CMDRAW_CHOICE_LONG_PRGTEXT:
CMDRAW_CHOICE_FUNC:
CMDRAW_CHOICE_LONG_FUNC:
CMDRAW_CHOICE_FUNC_PRGTEXT:
CMDRAW_CHOICE_LONG_FUNC_PRGTEXT:

; All of these just empty the rest of the row
CMDRAW_HEADER:
CMDRAW_PRESET:
CMDRAW_SUBMENU:
CMDRAW_SUBMENU_VARIABLE:
CMDRAW_FUNC:
	JMP EmptyCurrentRow_from_here_to_end



